ROLE_SKILLS = {
    "ML Engineer": {
    "Python": 0.9,
    "SQL": 0.7,
    "TensorFlow": 0.6,
    "PyTorch": 0.7,
    "Scikit-Learn": 0.8,
    "Docker": 0.6,
    "Kubernetes": 0.5,
    "Feature Engineering": 0.8,
    "Model Deployment": 0.8,
    "CI/CD": 0.6,
    "AWS": 0.7,
    "MLOps": 0.8
    },
    "Data Analyst": {
        "Python": 0.8,
        "SQL": 0.9,
        "Excel": 0.7,
        "Power BI": 0.6,
        "Statistics": 0.8
    },
    "Data Scientist": {
    "Python": 0.9,
    "Statistics": 0.85,
    "SQL": 0.8,
    "Machine Learning": 0.9,
    "Deep Learning": 0.7,
    "Data Visualization": 0.8,
    "Pandas": 0.8,
    "NumPy": 0.8,
    "Scikit-Learn": 0.85,
    "Feature Engineering": 0.75,
    "A/B Testing": 0.7,
    "Big Data": 0.6,
    "AWS": 0.6
    },
    "Backend Developer": {
    "Python": 0.9,
    "FastAPI": 0.8,
    "Django": 0.7,
    "SQL": 0.8,
    "PostgreSQL": 0.8,
    "MongoDB": 0.7,
    "Docker": 0.7,
    "Redis": 0.6,
    "System Design": 0.8,
    "API Design": 0.8,
    "Authentication": 0.7,
    "Microservices": 0.6,
    "AWS": 0.7
    },
    "Full Stack Developer": {
    "HTML": 0.9,
    "CSS": 0.8,
    "JavaScript": 0.9,
    "React": 0.8,
    "Node.js": 0.8,
    "SQL": 0.7,
    "MongoDB": 0.7,
    "Git": 0.8,
    "REST APIs": 0.8,
    "Docker": 0.6
    },
    "AI Engineer": {
    "Python": 0.9,
    "Machine Learning": 0.9,
    "Deep Learning": 0.85,
    "TensorFlow": 0.8,
    "PyTorch": 0.8,
    "Scikit-Learn": 0.75,
    "Data Preprocessing": 0.75,
    "Model Optimization": 0.7,
    "MLOps": 0.8,
    "Docker": 0.7,
    "Kubernetes": 0.6,
    "AWS": 0.7,
    "System Design": 0.7
    },
    "Cloud Engineer": {
    "AWS": 0.9,
    "Azure": 0.8,
    "Google Cloud": 0.8,
    "Docker": 0.8,
    "Kubernetes": 0.85,
    "Terraform": 0.8,
    "CI/CD": 0.8,
    "Linux": 0.85,
    "Networking": 0.8,
    "Python": 0.7,
    "Monitoring": 0.7,
    "Security": 0.8
    },
    "Business Analyst": {
    "Excel": 0.9,
    "SQL": 0.85,
    "Data Visualization": 0.8,
    "Power BI": 0.8,
    "Tableau": 0.75,
    "Business Analysis": 0.9,
    "Requirement Gathering": 0.85,
    "Stakeholder Management": 0.8,
    "Documentation": 0.75,
    "Statistics": 0.7,
    "Process Modeling": 0.75,
    "Communication Skills": 0.9
    },
    "NLP Engineer": {
    "Python": 0.9,
    "Machine Learning": 0.85,
    "Deep Learning": 0.85,
    "NLP": 0.95,
    "Transformers": 0.85,
    "Hugging Face": 0.8,
    "TensorFlow": 0.75,
    "PyTorch": 0.8,
    "Text Preprocessing": 0.8,
    "Model Deployment": 0.75,
    "MLOps": 0.7,
    "Statistics": 0.75
    },
    "Front End Developer": {
    "HTML": 0.95,
    "CSS": 0.9,
    "JavaScript": 0.95,
    "React": 0.9,
    "TypeScript": 0.8,
    "Redux": 0.7,
    "REST APIs": 0.8,
    "Git": 0.8,
    "Responsive Design": 0.85,
    "Performance Optimization": 0.75,
    "UI/UX Basics": 0.75,
    "Testing": 0.7
    },
}

LEARNING_RESOURCES = {
    "Machine Learning": ["Andrew Ng ML Course", "StatQuest"],
    "Deep Learning": ["DeepLearning.AI", "FastAI"],
    "MLOps": ["Made With ML", "Full Stack Deep Learning"],
    "Kubernetes": ["Kubernetes Docs", "KodeKloud"],
    "Terraform": ["Terraform Docs", "HashiCorp Tutorials"],
    "React": ["React Docs", "Net Ninja React"],
    "TypeScript": ["TypeScript Docs", "Academind"],
    "Transformers": ["HuggingFace Course"],
    "AWS": ["AWS Cloud Practitioner Course"],
    "Azure": ["Microsoft Learn Azure"],
    "Google Cloud": ["GCP Fundamentals"],
    "Business Analysis": ["IIBA Resources"],
}